parameters:
    version: 2
    db_type: mysql_dsn
    mysql_dsn: mysql://root:root@db:3306
    perm_type: none
    perm_user: www-data
    hosts_type: file
    httpd_type: apache24
    httpd_visibility: all
    httpd_shared_ports: '80'
    httpd_restart_command: 'sudo /usr/sbin/apachectl graceful'
services: {  }
